import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'gm-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.scss']
})
export class AutoGeneratedComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
